### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by alexAubin**
Apparently we forgot to create the testing PR ;P https://github.com/YunoHost-Apps/matomo_ynh/issues/29

## Changelog

- Update to 4.1.x ( https://github.com/YunoHost-Apps/matomo_ynh/pull/27 )
- Add change url script ( https://github.com/YunoHost-Apps/matomo_ynh/pull/23 )

### CODE REVIEW

**Comment by alexAubin** [comment]
(@ericgaspar : if you have a minute I'm not sure how to fix the conflict in scripts/upgrade)

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
(Ah in fact there's also a pending 4.1.1 branch ?)

**Comment by alexAubin** [comment]
(super quick review, LGTM)

**Comment by ericgaspar** [comment]
The latests 4.1.x updates seem to break the GeoIP plugin (https://github.com/matomo-org/matomo/issues/17023). It might be worth waiting for the next update to get this bug fixed.

**Comment by alexAubin** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
