### PR TITLE
Full upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/matomo_ynh%20PR7%20(yalh76)/)

### CODE REVIEW

**Comment by rndmh3ro** [comment]
I tested the PR. Installation works!

I did not get an email with the database-credentials - however seeing that you did not change anything there, I assume that it didn't work before, too.

**Comment by yalh76** [comment]
> 
> 
> I tested the PR. Installation works!
> 
> I did not get an email with the database-credentials - however seeing that you did not change anything there, I assume that it didn't work before, too.

Just tested and the mail is well received in root mailbox

**Comment by rndmh3ro** [comment]
Yeah, like I said, I think that's a problem in my side. I'm in favor of merging this pr.

**Comment by yalh76** [comment]
if someone from @YunoHost-Apps/apps-group can merge that PR :)

Thanks in advance

**Comment by kay0u** [comment]
Thank you!

**Pull request merged**
