### PR TITLE
Changed the URL of the sources to include all sub modules

### PR DESCRIPTION
**Pull request by lolusab**
## Problem

After installation, the git sub-modules (e.g. tag manager) are not present

## Solution

Instead of using the link of the GitHub archive, use the official link present in the documentation

I have tried a manual installation on a local instance. No error during installation.

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
Thanks for the PR 👍
We also need to adapt upgrade script as well.

**Comment by ericgaspar** [comment]
!testme

**Comment by lolusab** [comment]
With pleasure.

Sorry for the update script, I had forgotten it...

**Comment by ericgaspar** [comment]
> With pleasure.
> 
> Sorry for the update script, I had forgotten it...

Thanks for the work!
don't we need to keep the `core:update` function : `php$phpversion $final_path/console core:update -n`?

**Comment by lolusab** [comment]
Hey ! 

This will not be necessary as the modules are included in the package.

The order must return that the modules are up-to-date.

Nevertheless, you can leave the command in the script.

**Pull request merged**
